Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/srv/conda/envs/notebook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from collections import Counter, defaultdict
from itertools import combinations 
import pandas as pd
import numpy as np
import seaborn as sns
import operator
import math
import gensim
import itertools
from sklearn.feature_extraction import DictVectorizer
from sklearn import preprocessing, tree
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.feature_extraction import DictVectorizer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, ParameterGrid
import collections
import nltk
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings("ignore")
from sklearn.ensemble import RandomForestClassifier
# from nltk import word_tokenize, tokenize
# nltk.download('punkt')
import plotly.express as px
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

import scipy.stats as sc
from sklearn.metrics import mean_absolute_error, mean_squared_error

------------------

[0;31m------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m              Traceback (most recent call last)
Cell [0;32mIn[1], line 8[0m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01moperator[39;00m
[1;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mmath[39;00m
[0;32m----> 8[0m [38;5;28;01mimport[39;00m [38;5;21;01mgensim[39;00m
[1;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01mitertools[39;00m
[1;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfeature_extraction[39;00m [38;5;28;01mimport[39;00m DictVectorizer

[0;31mModuleNotFoundError[0m: No module named 'gensim'
ModuleNotFoundError: No module named 'gensim'

